[2022-04-30 03:16:38,388] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dataproc_bqext_bqpart_dag.bq_create_partitioned_table_task manual__2022-04-30T02:41:16.885061+00:00 [queued]>
[2022-04-30 03:16:38,411] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dataproc_bqext_bqpart_dag.bq_create_partitioned_table_task manual__2022-04-30T02:41:16.885061+00:00 [queued]>
[2022-04-30 03:16:38,413] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 03:16:38,415] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-04-30 03:16:38,417] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 03:16:38,444] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_partitioned_table_task> on 2022-04-30 02:41:16.885061+00:00
[2022-04-30 03:16:38,457] {standard_task_runner.py:52} INFO - Started process 1620 to run task
[2022-04-30 03:16:38,474] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dataproc_bqext_bqpart_dag', 'bq_create_partitioned_table_task', 'manual__2022-04-30T02:41:16.885061+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dataproc_spark_dagv3.py', '--cfg-path', '/tmp/tmpvnsqran5', '--error-file', '/tmp/tmpym2gsh7g']
[2022-04-30 03:16:38,479] {standard_task_runner.py:77} INFO - Job 12: Subtask bq_create_partitioned_table_task
[2022-04-30 03:16:38,605] {logging_mixin.py:109} INFO - Running <TaskInstance: dataproc_bqext_bqpart_dag.bq_create_partitioned_table_task manual__2022-04-30T02:41:16.885061+00:00 [running]> on host 2793a00d8448
[2022-04-30 03:16:38,709] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataproc_bqext_bqpart_dag
AIRFLOW_CTX_TASK_ID=bq_create_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T02:41:16.885061+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-30T02:41:16.885061+00:00
[2022-04-30 03:16:38,714] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-30 03:16:38,717] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-04-30 03:16:38,743] {bigquery.py:1637} INFO - Inserting job ***_dataproc_bqext_bqpart_dag_bq_create_partitioned_table_task_2022_04_30T02_41_16_885061_00_00_98dedaa980630ba23f5a26badeeff297
[2022-04-30 03:16:39,521] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))

(job ID: airflow_dataproc_bqext_bqpart_dag_bq_create_partitioned_table_task_2022_04_30T02_41_16_885061_00_00_98dedaa980630ba23f5a26badeeff297)

                                                                                 -----Query Job SQL Follows-----                                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE traffic_crashes_data.final_summary             PARTITION BY DATE(CRASH_DATE)             AS             SELECT * FROM traffic_crashes_data.final_summ_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-30 03:16:39,555] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=dataproc_bqext_bqpart_dag, task_id=bq_create_partitioned_table_task, execution_date=20220430T024116, start_date=20220430T031638, end_date=20220430T031639
[2022-04-30 03:16:39,639] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task bq_create_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))

(job ID: airflow_dataproc_bqext_bqpart_dag_bq_create_partitioned_table_task_2022_04_30T02_41_16_885061_00_00_98dedaa980630ba23f5a26badeeff297)

                                                                                 -----Query Job SQL Follows-----                                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE traffic_crashes_data.final_summary             PARTITION BY DATE(CRASH_DATE)             AS             SELECT * FROM traffic_crashes_data.final_summ_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-30 03:16:39,809] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 03:16:39,954] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
